# Frontend React App Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  namespace: cost-optimization
  labels:
    app: frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      nodeSelector:
        kubernetes.io/hostname: ip-10-0-3-78.ec2.internal
      containers:
      - name: frontend
        image: 703758695872.dkr.ecr.us-east-1.amazonaws.com/cost-optimization-frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: REACT_APP_API_URL
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "50m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: cost-optimization
  labels:
    app: frontend-app
spec:
  selector:
    app: frontend-app
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
