name: Build and Push Container Images

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual trigger

env:
  REGISTRY: ghcr.io
  GITHUB_REPOSITORY: ${{ github.repository }}
  BACKEND_IMAGE: ghcr.io/${{ github.repository }}/cost-optimization-backend
  FRONTEND_IMAGE: ghcr.io/${{ github.repository }}/cost-optimization-frontend
  DATABASE_IMAGE: ghcr.io/${{ github.repository }}/cost-optimization-database

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push backend image
      run: |
        cd backend
        docker build -t $BACKEND_IMAGE:$GITHUB_SHA .
        docker tag $BACKEND_IMAGE:$GITHUB_SHA $BACKEND_IMAGE:latest
        docker push $BACKEND_IMAGE:$GITHUB_SHA
        docker push $BACKEND_IMAGE:latest
        echo "Backend image pushed to GitHub Container Registry successfully"

    - name: Build and push frontend image
      run: |
        cd frontend/cost-dashboard
        docker build -t $FRONTEND_IMAGE:$GITHUB_SHA .
        docker tag $FRONTEND_IMAGE:$GITHUB_SHA $FRONTEND_IMAGE:latest
        docker push $FRONTEND_IMAGE:$GITHUB_SHA
        docker push $FRONTEND_IMAGE:latest
        echo "Frontend image pushed to GitHub Container Registry successfully"

    - name: Build and push database image
      run: |
        cd database
        docker build -t $DATABASE_IMAGE:$GITHUB_SHA .
        docker tag $DATABASE_IMAGE:$GITHUB_SHA $DATABASE_IMAGE:latest
        docker push $DATABASE_IMAGE:$GITHUB_SHA
        docker push $DATABASE_IMAGE:latest
        echo "Database image pushed to GitHub Container Registry successfully"

    - name: Output image URIs
      run: |
        echo "✅ All images built and pushed successfully to GitHub Container Registry!"
        echo "Backend: $BACKEND_IMAGE:latest"
        echo "Frontend: $FRONTEND_IMAGE:latest"
        echo "Database: $DATABASE_IMAGE:latest"
        echo ""
        echo "🌐 Images are publicly available at:"
        echo "https://github.com/${{ github.repository }}/pkgs/container/cost-optimization-backend"
        echo "https://github.com/${{ github.repository }}/pkgs/container/cost-optimization-frontend"
        echo "https://github.com/${{ github.repository }}/pkgs/container/cost-optimization-database"
